# Configuración de la fuente de datos H2 en memoria
#spring.datasource.url=jdbc:h2:mem:caidasdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
spring.datasource.url=jdbc:sqlite:fallen.db
spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=com.example.fallen.config.SQLiteDialect


jwt.secret=MySuperSecureJWTKeyThatIsAtLeast32CharsLong!
# Configuración de JPA (crear o actualizar las tablas automáticamente)
#spring.jpa.hibernate.ddl-auto=update
# Mostrar las sentencias SQL en la consola (opcional)
#spring.jpa.show-sql=true
# Consola de H2 habilitada (accesible en http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8085