# Configuración de la fuente de datos H2 en memoria
#spring.datasource.url=jdbc:h2:mem:caidasdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# SQLite persistente en el Volume de Railway
spring.datasource.url=jdbc:sqlite:/data/fallen.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Configuración de Hibernate / JPA
#spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=com.example.fallen.config.SQLiteDialect

# JWT
jwt.secret=MySuperSecureJWTKeyThatIsAtLeast32CharsLong!

# Configuración de JPA
#spring.jpa.hibernate.ddl-auto=update

# Mostrar las sentencias SQL en la consola
#spring.jpa.show-sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Puerto del servidor
server.port=${PORT:8085}